export const genres = {
   Avantura: "Avantura",
   Animirani: "Animirani",
   Akcija: "Akcija",
   Biografija: "Biografija",
   Dokumentarni: "Dokumentarni",
   Drama: "Drama",
   Familijarni: "Familijarni",
   Fantazija: "Fantazija",
   Horor: "Horor",
   Muzički: "Muzički",
   Komedija: "Komedija",
   Krimi: "Krimi",
   Istorijski: "Istorijski",
   Ratni: "Ratni",
   Romantični: "Romantični",
   Vestern: "Vestern",
   SciFi: "Sci-Fi",
   Triler: "Triler",
};

export default function moviesData() {
   //Zanr
   const {
      Avantura,
      Animirani,
      Akcija,
      Biografija,
      Dokumentarni,
      Drama,
      Familijarni,
      Fantazija,
      Horor,
      Muzički,
      Komedija,
      Krimi,
      Istorijski,
      Ratni,
      Romantični,
      Vestern,
      SciFi,
      Triler,
   } = genres;

   //Jezik
   const Domaci = "Domaci";
   const Engleski = "Engleski";

   //Quality
   const lowQ = "480p";
   const mediumQ = "720p";
   const HD = "1080p";
   const UHD = "2160p";

   const movies = [
      {
         id: "1",
         img: "/batman.jpg",
         label: "The Batman",
         text: "Kada sadistički serijski ubica počne da ubija ključne političke ličnosti u Gotamu, Betmen je primoran da istraži skrivenu korupciju u gradu i dovede u pitanje umešanost svoje porodice.",
         quality: UHD,
         genre: [Akcija, Krimi, Drama],
         year: 2022,
         imdb: 7.8,
         imdburl: "https://www.imdb.com/title/tt1877830/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_The%2520Batman",
         metascore: 72,
         metaurl: "https://www.metacritic.com/movie/the-batman/",
         tommato: 85,
         tomattoaudience: 87,
         tomattourl: "https://www.rottentomatoes.com/m/the_batman",
         laguange: Engleski,
         trailer: "mqqft2x_Aa4",
         story: "Dve godine noći pretvorile su Brusa Vejna u noćnu životinju. Ali dok nastavlja da pronalazi svoj put dok je Gotamov mračni vitez Brus primoran na igru mačke i miša sa svojom najvećom pretnjom do sada, maničnim ubicom poznatim kao „Zagonetka“ koji je ispunjen besom i odlučan da razotkrije korumpirani sistem dok izdvaja sve ključne političke ličnosti Gotama. Radeći sa uspostavljenim i novim saveznicima, Brus mora da pronađe ubicu i da ga privede pravdi, dok istražuje pravo nasleđe svog oca i dovodi u pitanje uticaj koji je on do sada imao na Gotam kao „Betmen“.",
         director: ["Matt Reeves"],
         writers: ["Matt Reeves", "Peter Craig", "Bob Kane"],
         actors: ["Robert Pattinson", "Zoë Kravitz", "Jeffrey Wright"],
         releaseDate: "March 4, 2022",
         runtime: "2h 56m",
         comments: {
            Milan: ["Odlican film", "8. Jan 2024."],
            Jovan: ["I nije nesto", "1. Jan 2024."],
            Petar: ["smorio...", ["9. Dev 2023."]],
         },
      },
      {
         id: "2",
         img: "/aquaman.jpg",
         label: "Aquaman",
         text: "Artur Kari, čovek rođen naslednik podvodnog kraljevstva Atlantide, kreće u potragu da spreči rat između svetova okeana i kopna.",
         quality: UHD,
         genre: [Akcija, Avantura, Fantazija],
         year: "2018",
         imdb: 6.8,
         imdburl: "https://www.imdb.com/title/tt1477834/?ref_=nv_sr_srsg_3_tt_8_nm_0_q_Aquaman",
         metascore: 55,
         metaurl: "https://www.metacritic.com/movie/aquaman/",
         tommato: 66,
         tomattoaudience: 72,
         tomattourl: "https://www.rottentomatoes.com/m/aquaman_2018",
         laguange: Engleski,
         trailer: "WDkg3h8PCVU",
         story: "Rođen na obalama površinskog sveta, Artur Kari (Džejson Momoa) otkriva da je samo napola čovek, a druga polovina njegove krvi je poreklom iz Atlantide, što ga čini zakonitim naslednikom trona podmorskog kraljevstva Atlantide. . Međutim, Artur saznaje da Atlantidom vlada njegov zlonamerni polubrat Orm (Patrik Vilson), koji nastoji da ujedini sedam podvodnih kraljevstava i vodi rat na površini. Uz pomoć Nuidisa Vulka (Vilem Defo) i prelepe Mere (Amber Herd), Artur mora da otkrije pun potencijal svoje prave sudbine i postane Akvamen kako bi spasio Atlantidu i površinu od Ormove zle zavere.",
         director: ["James Wan"],
         writers: ["David Leslie", "Johnson-McGoldrickWill", "BeallGeoff Johns"],
         actors: ["Jason Momoa", "Amber Heard", "Willem Dafoe "],
         releaseDate: "December 21, 2018",
         runtime: "2h 23m",
         comments: {
            Ana: ["Zanimljiva priča", "15. Feb 2024."],
            Nikola: ["Najbolji film ikad!", "3. Feb 2024."],
            Tamara: ["Nije loš, ali očekivala sam više.", "7. Feb 2024."],
         },
      },
      {
         id: "3",
         img: "/captain.jpg",
         label: "Captain America: Civil War",
         text: "Politička uključenost u poslove Osvetnika izaziva razdor između Kapetana Amerike i Iron Mana.",
         quality: UHD,
         genre: [Akcija, SciFi],
         year: 2016,
         imdb: 7.8,
         imdburl: "https://www.imdb.com/title/tt3498820/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Captain%2520America%253A%2520Civil%2520War",
         metascore: 75,
         metaurl: "https://www.metacritic.com/movie/captain-america-civil-war/",
         tommato: 66,
         tomattoaudience: 72,
         tomattourl: "https://www.rottentomatoes.com/m/aquaman_2018",
         laguange: Engleski,
         trailer: "dKrVegVI0Us",
         story: "S obzirom da se mnogi ljudi plaše postupaka superheroja, vlada odlučuje da progura Zakon o registraciji heroja, zakon koji ograničava djelovanje heroja. Ovo rezultira podjelom u Osvetnicima. Iron Man stoji uz ovaj zakon, tvrdeći da se njihova djela moraju držati pod kontrolom, inače će gradovi i dalje biti uništeni, ali Kapetan Amerika smatra da je spašavanje svijeta dovoljno hrabro i da se ne mogu osloniti na vladu da zaštiti svijet. Ovo eskalira u sveopšti rat između tima Iron Man (Iron Man, Black Panther, Vision, Black Widow, War Machine i Spider-Man) i Team Captain America (Kapetan Amerika, Bucky Barnes, Falcon, Scarlet Witch, Hawkeye, i Ant Man) dok se pojavljuje novi zlikovac.",
         director: ["Anthony Russo", "Joe Russo"],
         writers: ["Christopher Markus", "Stephen McFeely", "Joe Simon"],
         actors: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson"],
         releaseDate: "May 6, 2016",
         runtime: "2h 27m",
         comments: {
            Luka: ["Preporučujem svima!", "12. Jan 2024."],
            Jovana: ["Zabavan film", "19. Jan 2024."],
            Stefan: ["Očekivao sam bolje", "5. Jan 2024."],
         },
      },
      {
         id: "4",
         img: "/joker.jpg",
         label: "Joker",
         text: "Tokom 1980-ih, propali stand-up komičar izluđuje i okreće se životu u kriminalu i haosu u Gotam Sitiju, dok postaje zloglasna psihopatska kriminalna figura.",
         quality: UHD,
         genre: [Krimi, Drama, Triler],
         year: 2019,
         imdb: 8.4,
         imdburl: "https://www.imdb.com/title/tt7286456/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_joker",
         metascore: 59,
         metaurl: "https://www.metacritic.com/movie/joker/",
         tommato: 69,
         tomattoaudience: 88,
         tomattourl: "https://www.rottentomatoes.com/m/joker_2019",
         laguange: Engleski,
         trailer: "zAGVQLHvwOY",
         story: "Društveno nesposoban klovn koji se iznajmljuje - Arthur Fleck teži da bude stand up komičar na svom malom poslu koji radi obučen kao klovn koji drži natpis za oglašavanje. On se brine o svojoj majci, Penny Fleck, i kako saznaje više o svojoj mentalnoj bolesti, saznaje više o svojoj prošlosti. Suočavajući se sa svom negativnošću i maltretiranjem iz društva, on se kreće naniže po spirali, zauzvrat pokazujući kako je nastao njegov alter ego, 'Joker'.",
         director: ["Todd Phillips"],
         writers: ["Todd Phillips", "Scott Silver", "Bob Kane"],
         actors: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
         releaseDate: "October 4, 2019",
         runtime: "2h 2m",
         comments: {
            Milica: ["Odličan izbor glumaca", "22. Dec 2023."],
            Marko: ["Nije loše, ali ne bih ga gledao opet", "10. Dec 2023."],
            Teodora: ["Dosadan film", "28. Dec 2023."],
         },
      },
      {
         id: "5",
         img: "/spidermab.jpg",
         label: "Spider-Man",
         text: "Nakon što ga ugrize genetski modificirani pauk, sramežljivi tinejdžer stječe sposobnosti poput pauka koje koristi da se bori protiv nepravde kao maskirani superheroj i suoči se sa osvetoljubivim neprijateljem.",
         quality: mediumQ,
         genre: [Akcija, Avantura, SciFi],
         year: 2002,
         imdb: 7.4,
         imdburl: "https://www.imdb.com/title/tt0145487/?ref_=nv_sr_srsg_3_tt_8_nm_0_q_Spider-Man",
         metascore: 73,
         metaurl: "https://www.metacritic.com/movie/spider-man/",
         tommato: 90,
         tomattoaudience: 67,
         tomattourl: "https://www.rottentomatoes.com/m/spiderman",
         laguange: Engleski,
         trailer: "t06RUxPbp_c",
         story: "Zasnovana na liku superheroja iz Marvel Comicsa, ovo je priča o Peteru Parkeru koji je štreber u srednjoj školi. Bio je siroče kao dijete, maltretirani od strane sportista i ne može priznati svoju simpatiju u svoju zadivljujuću djevojku iz susjedstva Mary Jane Watson. Reći da je njegov život 'jadan' je malo reći. Ali jednog dana dok je bio na ekskurziji u laboratoriju, odbjegli radioaktivni pauk ga je ugrizao... i njegov život se mijenja na način koji niko nije mogao zamisliti. Peter stječe mišićnu tjelesnu građu, jasan vid, sposobnost da se drži za površine i puzi po zidovima, pucajući mrežama sa svog zgloba... ali zabava neće potrajati. Ekscentrični milioner Norman Osborn daje sebi drogu koja poboljšava performanse i pojavljuje se njegov manijakalni alter ego Green Goblin. Sada Peter Parker mora postati Spider-Man i odvesti Zelenog Goblina na zadatak... ili će ga Goblin ubiti. Oni se susreću licem u lice i počinje rat u kojem će samo jedan od njih preživjeti na kraju.",
         director: ["Sam Raimi"],
         writers: ["Stan Lee", "Steve Ditko", "David Koepp"],
         actors: ["Tobey Maguire", "Kirsten Dunst", "Willem Dafoe"],
         releaseDate: "May 3, 2002",
         runtime: "2h 1m",
         comments: {
            Nemanja: ["Nisam mogao prestati gledati!", "14. Nov 2023."],
            Marija: ["Moglo je bolje", "2. Nov 2023."],
            Aleksandar: ["Gledljivo, ali ništa posebno", "8. Nov 2023."],
         },
      },
      {
         id: "6",
         img: "/Shawshank.jpg",
         label: "The Shawshank Redemption",
         text: "Tokom nekoliko godina dvoje osuđenika sklapaju prijateljstvo, tražeći utjehu i, na kraju, iskupljenje kroz osnovno saosećanje.",
         quality: "720p",
         genre: [Drama],
         year: 1994,
         imdb: 9.3,
         imdburl: "https://www.imdb.com/title/tt0111161/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Shawshank",
         metascore: 82,
         metaurl: "https://www.metacritic.com/movie/the-shawshank-redemption/",
         tommato: 91,
         tomattoaudience: 98,
         tomattourl: "https://www.rottentomatoes.com/m/shawshank_redemption",
         laguange: Engleski,
         trailer: "PLl99DlL6b4",
         story: "Hronika iskustva nekadašnjeg uspješnog bankara kao zatvorenika u sumornom zatvoru u Shawshanku nakon što je proglašen krivim za zločin koji nije počinio. Film prikazuje čovjekov jedinstven način suočavanja sa svojim novim, mučnim životom; usput se sprijatelji sa brojnim zatvorenicima, među kojima je najistaknutiji mudri zatvorenik po imenu Red.",
         director: ["Frank Darabont"],
         writers: ["Stephen King", "Frank Darabont"],
         actors: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
         releaseDate: "October 14, 1994",
         runtime: "2h 22m",
         comments: {
            Ivana: ["Savršeno!", "17. Oct 2023."],
            Vuk: ["Ne bih ga preporučio", "25. Oct 2023."],
            Milos: ["Očekivao sam više", "31. Oct 2023."],
         },
      },
      {
         id: "7",
         img: "/Godfather.jpg",
         label: "The Godfather",
         text: "Don Vito Corleone, glava mafijaške porodice, odlučuje predati svoje carstvo svom najmlađem sinu Michaelu. Međutim, njegova odluka nenamjerno dovodi živote njegovih najmilijih u ozbiljnu opasnost.",
         quality: "720p",
         genre: [Krimi, Drama],
         year: 1972,
         imdb: 9.2,
         imdburl: "https://www.imdb.com/title/tt0068646/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_The%2520Godfather",
         metascore: 100,
         metaurl: "https://www.metacritic.com/movie/the-godfather/",
         tommato: 97,
         tomattoaudience: 98,
         tomattourl: "https://www.rottentomatoes.com/m/the_godfather",
         laguange: Engleski,
         trailer: "sY1S34973zA",
         story: "Kum 'Don' Vito Corleone je glava mafijaške porodice Corleone u New Yorku. On je na svadbi svoje ćerke. Mihael, Vitov najmlađi sin i odlikovani marinac iz Drugog svetskog rata takođe je prisutan na venčanju. Čini se da Michael nije zainteresiran da bude dio porodičnog posla. Vito je moćan čovjek, ljubazan je prema svima koji ga poštuju, ali je nemilosrdan prema onima koji to ne čine. Ali kada moćni i podmukli rival želi da prodaje drogu i za to mu je potreban Donov uticaj, Vito to odbija. Ono što slijedi je sukob između Vitovih blijedih starih vrijednosti i novih načina koji bi mogli navesti Michaela da uradi ono što je najviše oklijevao i povede mafijaški rat protiv svih ostalih mafijaških porodica koji bi mogli razdvojiti porodicu Corleone.",
         director: ["Francis Ford Coppola"],
         writers: ["Mario Puzo", "Francis Ford Coppola"],
         actors: ["Marlon Brando", "Al Pacino", " James Caan"],
         releaseDate: "March 24, 1972",
         runtime: "2h 55m",
         comments: {
            Jelena: ["Ne znam što svi hvale...", "9. Sep 2023."],
            Dusan: ["Sjajan scenarij", "27. Sep 2023."],
            Katarina: ["Bolje nego što sam očekivala", "15. Sep 2023."],
         },
      },
      {
         id: "8",
         img: "/darkknight.jpg",
         label: "The Dark Knight",
         text: "Kada prijetnja poznata kao Joker izazove pustoš i haos ljudima u Gotamu, Batman mora prihvatiti jedan od najvećih psiholoških i fizičkih testova svoje sposobnosti da se bori protiv nepravde.",
         quality: "1080p",
         genre: [Krimi, Drama, Akcija],
         year: 2008,
         imdb: 9.0,
         imdburl: "https://www.imdb.com/title/tt0468569/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_The%2520Dark%2520Knight",
         metascore: 84,
         metaurl: "https://www.metacritic.com/movie/the-dark-knight/",
         tommato: 94,
         tomattoaudience: 94,
         tomattourl: "https://www.rottentomatoes.com/m/the_dark_knight",
         laguange: Engleski,
         trailer: "EXeTwQWrcwY",
         story: `Smješten u roku od godinu dana nakon događaja u filmu Batman Begins (2005), Batman, poručnik James Gordon i novi okružni tužilac Harvey Dent uspješno počinju prikupljati kriminalce koji muče Gotham City, sve dok misteriozni i sadistički zločinački mozak poznat samo kao "The Joker" se pojavljuje u Gothamu, stvarajući novi talas haosa. Batmanova borba protiv Džokera postaje duboko lična, prisiljavajući ga da se "suoči sa svime u šta vjeruje" i poboljša svoju tehnologiju kako bi ga zaustavio. Ljubavni trokut se razvija između Bruce Waynea, Denta i Rachel Dawes.`,
         director: ["Christopher Nolan"],
         writers: ["Jonathan Nolan", "Christopher Nolan", "David S. Goyer"],
         actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
         releaseDate: "July 18, 2008",
         runtime: "2h 32m",
         comments: {
            Nikola: ["Nije za svakoga", "4. Aug 2023."],
            Sara: ["Plačem od smeha!", "12. Aug 2023."],
            Andrija: ["Gubi se u drugom dijelu", "20. Aug 2023."],
         },
      },
      {
         id: "9",
         img: "/Godfather2.jpg",
         label: "The Godfather Part II",
         text: "Prikazan je rani život i karijera Vita Corleonea u New Yorku 1920-ih, dok njegov sin Michael proširuje i jača svoj stisak nad sindikatom porodičnog kriminala.",
         quality: "720p",
         genre: [Krimi, Drama],
         year: 1976,
         imdb: 10,
         imdburl: "https://www.imdb.com/title/tt0071562/?ref_=nv_sr_srsg_0_tt_7_nm_1_q_The%2520Godfather%2520Part%2520II",
         metascore: 90,
         metaurl: "https://www.metacritic.com/movie/the-godfather-part-ii/",
         tommato: 96,
         tomattoaudience: 97,
         tomattourl: "https://www.rottentomatoes.com/m/godfather_part_ii",
         laguange: Engleski,
         trailer: "9O1Iy9od7-A",
         story: `Nastavak sage o kriminalnoj porodici Corleone priča priču o mladom Vitu Corleoneu koji je odrastao na Siciliji iu New Yorku 1910-ih; i prati Michaela Corleonea 1950-ih dok pokušava proširiti porodični biznis na Las Vegas, Hollywood i Kubu`,
         director: ["Francis Ford Coppola"],
         writers: ["Francis Ford Coppola", "Mario Puzo"],
         actors: ["Al Pacino", "Robert De Niro", "Robert Duvall"],
         releaseDate: "December 18, 1974",
         runtime: "3h 22m",
         comments: {
            Tamara: ["Sjajna glazba", "1. Jul 2023."],
            Filip: ["Moraš ga pogledati!", "9. Jul 2023."],
            Ivana: ["Jedva čekam nastavak", "18. Jul 2023."],
         },
      },
      {
         id: "10",
         img: "/12angry.jpg",
         label: "12 Angry Men",
         text: "Porotu na suđenju za ubistvo u New Yorku frustrira jedan član čiji skeptični oprez primorava da pažljivije razmotre dokaze prije nego što preskoče na ishitrenu presudu.",
         quality: "480p",
         genre: [Krimi, Drama],
         year: 1957,
         imdb: 10,
         imdburl: "https://www.imdb.com/title/tt0050083/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_12%2520Angry%2520Men",
         metascore: 97,
         metaurl: "https://www.metacritic.com/movie/12-angry-men/",
         tommato: 100,
         tomattoaudience: 97,
         tomattourl: "https://www.rottentomatoes.com/m/1000013_12_angry_men",
         laguange: Engleski,
         trailer: "TEN-2uTi2c0",
         story: `Odbrana i tužilaštvo su se odmorili, a porota ulazi u prostoriju za porotu da odluči da li je mladić kriv ili nevin za ubistvo svog oca. Ono što počinje kao otvoreni i zatvoren slučaj ubistva ubrzo postaje detektivska priča koja predstavlja niz tragova koji stvaraju sumnju, i mini-dramu o predrasudama i predrasudama porotnika o suđenju, optuženima I jedni drugima . Na osnovu predstave, sva radnja se odvija na sceni sobe žirija.`,
         director: ["Sidney Lumet"],
         writers: ["Reginald Rose"],
         actors: ["Henry Fonda", "Lee J. Cobb", "Martin Balsam"],
         releaseDate: "April 10, 1957",
         runtime: "1h 36m",
         comments: {
            Stefan: ["Nema ništa posebno", "25. Jun 2023."],
            Mia: ["Iznenađujuće dobar", "3. Jun 2023."],
            Vladimir: ["Gubi se radnja", "11. Jun 2023."],
         },
      },
      {
         id: "11",
         img: "/Schindler.jpg",
         label: "Schindler's List",
         text: "U Nemačkoj okupiranoj Poljskoj tokom Drugog svetskog rata, industrijalac Oskar Šindler postepeno postaje zabrinut za svoju jevrejsku radnu snagu nakon što je bio svedok njihovog progona od strane nacista.",
         quality: "720p",
         genre: [Biografija, Drama, Istorijski],
         year: 1993,
         imdb: 9.0,
         imdburl: "https://www.imdb.com/title/tt0108052/?ref_=nv_sr_srsg_0_tt_7_nm_1_q_Schindler%27s%2520List",
         metascore: 95,
         metaurl: "https://www.metacritic.com/movie/schindlers-list/",
         tommato: 93,
         tomattoaudience: 93,
         tomattourl: "https://www.rottentomatoes.com/m/schindlers_list_25th_anniversary",
         laguange: Engleski,
         trailer: "gG22XNhtnoY",
         story: `Oskar Schindler je tašti i pohlepni njemački biznismen koji postaje nevjerovatan humanitarac usred varvarske vladavine njemačkih nacista kada se osjeća primoranim da svoju tvornicu pretvori u utočište za Jevreje. Zasnovan na istinitoj priči o Oskaru Šindleru koji je uspio spasiti oko 1100 Jevreja od gašenja u koncentracionom logoru Auschwitz, svedočanstvo je dobrog u svima nama.`,
         director: ["Steven Spielberg"],
         writers: ["Thomas Keneally", "Steven Zaillian"],
         actors: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley"],
         releaseDate: "February 4, 1994",
         runtime: "3h 15m",
         comments: {
            Jovana: ["Nisam mogao/la prestati gledati!", "19. May 2023."],
            Nemanja: ["Očekivao sam bolje", "27. May 2023."],
            Ana: ["Jedva čekam da ga pogledam opet", "5. May 2023."],
         },
      },
      {
         id: "12",
         img: "/ReturnoftheKing.jpg",
         label: "The Lord of the Rings: The Return of the King",
         text: "Gandalf i Aragorn predvode svijet ljudi protiv Sauronove vojske kako bi skrenuli njegov pogled sa Froda i Sama dok se približavaju Mount Doom s Jedinstvenim prstenom.",
         quality: "2160p",
         genre: [Akcija, Avantura, Drama],
         year: 2003,
         imdb: 9.0,
         imdburl:
            "https://www.imdb.com/title/tt0167260/?ref_=nv_sr_srsg_0_tt_1_nm_7_q_The%2520Lord%2520of%2520the%2520Rings%253A%2520The%2520Return%2520o",
         metascore: 94,
         metaurl: "https://www.metacritic.com/movie/the-lord-of-the-rings-the-return-of-the-king/",
         tommato: 94,
         tomattoaudience: 86,
         tomattourl: "https://www.rottentomatoes.com/m/the_lord_of_the_rings_the_return_of_the_king",
         laguange: Engleski,
         trailer: "r5X-hFf6Bwo",
         story: `Konačna konfrontacija između sila dobra i zla koje se bore za kontrolu nad budućnošću Međuzemlja. Frodo i Sam stižu do Mordora u potrazi da unište Jedinstveni Prsten, dok Aragorn predvodi snage dobra protiv Sauronove zle vojske u kamenom gradu Minas Tirith.`,
         director: ["Peter Jackson"],
         writers: ["J.R.R. Tolkien", "Fran Walsh", "Philippa Boyens"],
         actors: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
         releaseDate: "December 17, 2003",
         runtime: "3h 21m",
         comments: {
            Nikola: ["Nešto sasvim novo!", "13. Apr 2023."],
            Marija: ["Moglo je bolje", "21. Apr 2023."],
            Luka: ["Preporučujem svima!", "29. Apr 2023."],
         },
      },
      {
         id: "13",
         img: "/Interstellar.jpg",
         label: "Interstellar",
         text: "Kada Zemlja u budućnosti postane nenastanjiva, farmer i bivši pilot NASA-e, Joseph Cooper, ima zadatak da pilotira svemirskom letjelicom, zajedno s timom istraživača, da pronađe novu planetu za ljude.",
         quality: "2160p",
         genre: [Avantura, Drama, SciFi],
         year: 2014,
         imdb: 8.7,
         imdburl: "https://www.imdb.com/title/tt0816692/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Interstellar",
         metascore: 74,
         metaurl: "https://www.metacritic.com/movie/interstellar/",
         tommato: 73,
         tomattoaudience: 86,
         tomattourl: "https://www.rottentomatoes.com/m/interstellar_2014",
         laguange: Engleski,
         trailer: "zSWdZVtXT7E",
         story: `Budućnost Zemlje je prožeta katastrofama, glađu i sušama. Postoji samo jedan način da se osigura opstanak čovječanstva: međuzvjezdano putovanje. Novootkrivena crvotočina u udaljenim krajevima našeg Sunčevog sistema omogućava timu astronauta da ode tamo gdje nijedan čovjek nije išao, planetu koja možda ima pravo okruženje za održavanje ljudskog života.`,
         director: ["Christopher Nolan"],
         writers: ["Jonathan Nolan", "Christopher Nolan"],
         actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
         releaseDate: "November 7, 2014",
         runtime: "2h 49m",
         comments: {
            Teodora: ["Nisam očekivala ovakav kraj", "6. Mar 2023."],
            Aleksandar: ["Očekivao sam više", "14. Mar 2023."],
            Nina: ["Zanimljiva radnja", "22. Mar 2023."],
         },
      },
      {
         id: "14",
         img: "/SilenceLambs.jpg",
         label: "The Silence of the Lambs",
         text: "Mladi F.B.I. kadet mora dobiti pomoć zatvorenog i manipulativnog ubice ljudoždera kako bi pomogao uhvatiti drugog serijskog ubicu, luđaka koji ode kožu sa svojih žrtava.",
         quality: "720p",
         genre: [Krimi, Drama, Triler],
         year: 1991,
         imdb: 8.6,
         imdburl: "https://www.imdb.com/title/tt0102926/?ref_=nv_sr_srsg_1_tt_1_nm_6_q_The%2520Silence%2520of%2520the%2520Lambs",
         metascore: 86,
         metaurl: "https://www.metacritic.com/movie/the-silence-of-the-lambs/",
         tommato: 95,
         tomattoaudience: 95,
         tomattourl: "https://www.rottentomatoes.com/m/silence_of_the_lambs",
         laguange: Engleski,
         trailer: "6iB21hsprAQ",
         story: `F.B.I. pripravnica Clarice Starling (Jodie Foster) naporno radi kako bi unaprijedila svoju karijeru, dok pokušava sakriti ili staviti iza svojih korijena iz Zapadne Virdžinije, za koje bi je, da su neki znali, automatski klasificirali kao zaostalo ili bijelo smeće. Nakon diplomiranja, želi raditi u Odjeljenju za nauku o ponašanju agencije pod vodstvom Jacka Crawforda (Scott Glenn). Dok je još uvijek pripravnik, Crawford je traži da ispita dr. Hannibala Lectera (Sir Anthony Hopkins), psihijatra koji je do sada bio zatvoren osam godina u maksimalnoj sigurnosnoj izolaciji jer je bio serijski ubica koji je kanibalizirao svoje žrtve. Clarice može shvatiti da je zadatak da odabere Lecterov mozak kako bi im pomogao da riješe još jedan slučaj serijskog ubistva, slučaj nekoga koga su mediji izmislili kao "Buffalo Bill" (Ted Levine), a koji je do sada ubio pet žrtava, a sve se nalaze u na istoku SAD-a, sve mlade žene, koje imaju malo viška kilograma (posebno oko bokova), sve koje su se udavile u prirodnim vodama i sve kojima su skinuli veliki komadi kože. Također pretpostavlja da ju je Crawford odabrao, kao ženu, kako bi mogao izazvati neki emocionalni odgovor od Lectera. Nakon što je prvi put razgovarala s Lecterom, ona shvaća da će sve s njim biti psihološka igra, pri čemu će često morati da čita između vrlo zagonetnih redova koje on daje. Ona mora odlučiti koliko će se slagati, jer je njegov zahtjev za razgovor s njim da mu se emocionalno izloži. Slučaj dobija još strašniji zaokret kada se otkrije šesta žrtva, ova od koje su u stanju da izvuku ključni dokaz, ako je Lecter otvoren u pogledu njegovog značenja. Potencijalna sedma žrtva je Catherine Martin (Brooke Smith), kćerka senatora Ruth Martin (Diane Baker), koja više ispituje slučaj dok tragaju za, nadamo se, još živom Catherine. Onaj koji može da utiče na ono što se dešava je dr. Frederick Chilton (Anthony Heald), upravnik u zatvoru, oportunista koji vidi veći profil sa Catherine, što znači viši profil za sebe ako se može uspješno uključiti u postupak.`,
         director: ["Jonathan Demme"],
         writers: ["Thomas Harris", "Ted Tally"],
         actors: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
         releaseDate: "February 14, 1991",
         runtime: "1h 58m",
         comments: {
            Ivan: ["Savršeno!", "30. Jan 2023."],
            Milica: ["Dosadan film", "7. Feb 2023."],
            Marko: ["Nije loše, ali ništa posebno", "15. Feb 2023."],
         },
      },
      {
         id: "15",
         img: "/greenmile.jpg",
         label: "The Green Mile",
         text: "Priča smještena na smrtnu kaznu u južnom zatvoru, gdje nježni div John posjeduje misterioznu moć da liječi ljudske bolesti. Kada glavni čuvar, Paul, prepozna Johnov dar, pokušava pomoći da se spriječi pogubljenje osuđenog čovjeka.",
         quality: "720p",
         genre: [Krimi, Drama, Fantazija],
         year: 1999,
         imdb: 8.6,
         imdburl: "https://www.imdb.com/title/tt0120689/?ref_=nv_sr_srsg_0_tt_7_nm_1_q_The%2520Green%2520Mile",
         metascore: 61,
         metaurl: "https://www.metacritic.com/movie/the-green-mile/",
         tommato: 79,
         tomattoaudience: 94,
         tomattourl: "https://www.rottentomatoes.com/m/green_mile",
         laguange: Engleski,
         trailer: "Ki4haFrqSrw",
         story: `Zasnovan na istoimenom romanu Stivena Kinga iz 1996. Glumi Tom Hanks kao osuđenik na smrt tokom Velike depresije u SAD koji svjedoči natprirodnim događajima koji se događaju nakon što je zagonetni zatvorenik (Michael Clarke Duncan) doveden u njegovu ustanovu.`,
         director: ["Frank Darabont"],
         writers: ["Stephen King", "Frank Darabont"],
         actors: ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
         releaseDate: "December 10, 1999",
         runtime: "3h 9m",
         comments: {
            Jovana: ["Odličan izbor glumaca", "23. Dec 2022."],
            Stefan: ["Nije loš, ali očekivao sam više.", "31. Dec 2022."],
            Tamara: ["Zabavan film", "8. Jan 2023."],
         },
      },
      {
         id: "16",
         img: "/deerhunter.jpg",
         label: "The Deer Hunter",
         text: "Detaljno ispitivanje načina na koje Vijetnamski rat utiče i remeti živote nekoliko prijatelja u malom gradu čeličane u Pensilvaniji.",
         quality: "480p",
         genre: [Drama, Ratni],
         year: 1978,
         imdb: 8.0,
         imdburl: "https://www.imdb.com/title/tt0077416/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_The%2520Deer%2520Hunter",
         metascore: 86,
         metaurl: "https://www.metacritic.com/movie/the-deer-hunter/",
         tommato: 86,
         tomattoaudience: 91,
         tomattourl: "https://www.rottentomatoes.com/m/the_deer_hunter",
         laguange: Engleski,
         trailer: "g7q1SjVdsNk",
         story: `Michael, Steven i Nicky su 3 najbolja prijatelja koji često uživaju u lovu na jelene. Ovi muškarci bivaju angažovani da odu u Vijetnam kako bi se borili za svoju zemlju i proslavili oproštajnom žurkom, kao i Steven koji se oženi trudnom ženom po imenu "Angela". Nakon užasa tokom rata i igara ruskog ruleta koje su ovi ljudi prisiljeni igrati, Michael se vraća kući i shvaća da njegovi izleti u lov na jelene više nisu isti kao što su bili prije, zbog rata i on na kraju saznaje da je Steven hendikepiran i da se Nicky nije vratio iz Vijetnama, te se kao odgovor vraća u Vijetnam da ga spasi.`,
         director: ["Michael Cimino"],
         writers: ["Michael Cimino", "Deric Washburn", "Louis Garfinkle"],
         actors: ["Robert De Niro", "Christopher Walken", "John Cazale"],
         releaseDate: "February 23, 1979",
         runtime: "3h 3m",
         comments: {
            Nikola: ["Najbolji film ikad!", "16. Nov 2022."],
            Luka: ["Nisam loš film, ali nije za svakoga", "24. Nov 2022."],
            Ana: ["Očekivala sam bolje", "2. Dec 2022."],
         },
      },
      {
         id: "17",
         img: "/Kototamopeva.jpg",
         label: "Ko to tamo peva",
         text: "5. aprila 1941. godine negde u Srbiji. Grupa ljudi odlazi autobusom za Beograd, na putovanje koje će im zauvek promeniti život.",
         quality: mediumQ,
         genre: [Avantura, Drama, Komedija],
         year: 1980,
         imdb: 8.7,
         imdburl: "https://www.imdb.com/title/tt0076276/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_ko%2520to%2520tamo",
         metascore: 97,
         metaurl: "",
         tommato: 97,
         tomattoaudience: 97,
         tomattourl: "https://www.rottentomatoes.com/m/ko-to-tamo-peva-who-sings-over-there",
         laguange: Domaci,
         trailer: "90baIbTByjw",
         story: `5. aprila 1941. godine, datuma koji će Srbi prepoznati, u Krstićev autobus za Beograd ulaze muškarci na seoskom putu: dva Cigana koji povremeno pevaju o bedi, ostareli ratni veteran, simpatizer nacista, bezobrazni pevač, potrošeni čovek i čovek sa sačmarom. Krstić je cinik koji je umoran od sveta, za par dolar; vozač je njegov sin, jednostavni, veseli Miško. Na putu pokupe svećenika i mlade mladence koji idu na more. Na putu se dešavaju nesrećne avanture: probušena guma, klimav most, farmer koji je preorao cestu, sahrana, dve zavađene porodice, vojni deo i izgubljeni novčanik usporavaju autobus i razotkrivaju razdor među putnicima. 6. aprila, usred glasina o ratu, stižu do Beograda.`,
         director: ["Slobodan Sijan"],
         writers: ["Dusan Kovacevic"],
         actors: ["Pavle Vuisic", "Dragan Nikolic", "Danilo 'Bata' Stojkovic"],
         releaseDate: "June 30, 1980",
         runtime: "1h 26m",
         comments: {
            Mia: ["Sjajna glazba", "10. Oct 2022."],
            Filip: ["Jedva čekam nastavak", "18. Oct 2022."],
            Vladimir: ["Bolje nego što sam očekivao", "26. Oct 2022."],
         },
      },
      {
         id: "18",
         img: "/rickandmorty.jpg",
         label: "Rick and Morty",
         text: "Polomljeni domaći životi nihilističkog ludog naučnika i njegovog anksioznog unuka dodatno su komplikovani njihovim međudimenzionalnim nesrećama.",
         quality: UHD,
         genre: [Animirani, Avantura, Komedija],
         year: 2013,
         imdb: 9.1,
         imdburl: "https://www.imdb.com/title/tt2861424/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Rick%2520and%2520Morty",
         metascore: 85,
         metaurl: "https://www.metacritic.com/tv/rick-morty/",
         tommato: 90,
         tomattoaudience: 83,
         tomattourl: "https://www.rottentomatoes.com/tv/rick_and_morty",
         laguange: Engleski,
         trailer: "BFTSrbB2wII",
         story: `Animirana serija o plivanju za odrasle o beskonačnim avanturama Rika, genijalnog alkoholičara i nemarnog naučnika, sa svojim unukom Mortyjem, 14-godišnjim anksioznim dječakom koji nije toliko pametan. Zajedno istražuju beskonačne svemire; izazivaju haos i upadaju u nevolje.`,
         director: ["Dan Harmon", "Justin Roiland"],
         writers: ["Dan Harmon", "Justin Roiland"],
         actors: ["Chris Parnell", "Spencer Grammer", "Sarah Chalke"],
         releaseDate: "December 2, 2013",
         runtime: "23m",
         comments: {
            Nina: ["Nisam mogla prestati gledati!", "3. Sep 2022."],
            Ivan: ["Gubi se u drugom dijelu", "11. Sep 2022."],
            Milica: ["Moraš ga pogledati!", "19. Sep 2022."],
         },
      },
      {
         id: "19",
         img: "/mario.jpg",
         label: "The Super Mario Bros. Movie",
         text: "Vodoinstalater po imenu Mario putuje kroz podzemni lavirint sa svojim bratom Luiđijem, pokušavajući da spasi zarobljenu princezu.",
         quality: UHD,
         genre: [Animirani, Avantura, Komedija],
         year: 2023,
         imdb: 7.0,
         imdburl: "https://www.imdb.com/title/tt6718170/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_The%2520Super%2520Mario%2520Bros.%2520Movie",
         metascore: 46,
         metaurl: "https://www.metacritic.com/movie/the-super-mario-bros-movie/",
         tommato: 59,
         tomattoaudience: 95,
         tomattourl: "https://www.rottentomatoes.com/m/the_super_mario_bros_movie",
         laguange: Engleski,
         trailer: "TnGl01FkMMo",
         story: `Vodoinstalater iz Bruklina po imenu Mario putuje kroz Kraljevstvo gljiva s princezom po imenu Breskva i antropomorfnom gljivom po imenu Toad kako bi pronašao Mariovog brata Luigija i spasio svijet od nemilosrdne Koope koja diše vatru po imenu Bowser.`,
         director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
         writers: ["Matthew Fogel"],
         actors: ["Chris Pratt", "Anya Taylor-Joy", "Charlie Day"],
         releaseDate: "April 5, 2023",
         runtime: "1h 32m",
         comments: {
            Marko: ["Zanimljiva priča", "27. Aug 2022."],
            Teodora: ["Ne bih ga preporučila", "4. Sep 2022."],
            Aleksandar: ["Preporučujem svima!", "12. Sep 2022."],
         },
      },
      {
         id: "20",
         img: "/polarexe.jpg",
         label: "The Polar Express",
         text: "Na Badnje veče, dječak kreće u čarobnu avanturu na Sjeverni pol na Polar Expressu, dok uči o prijateljstvu, hrabrosti i duhu Božića.",
         quality: HD,
         genre: [Animirani, Avantura, Komedija],
         year: 2004,
         imdb: 6.6,
         imdburl: "https://www.imdb.com/title/tt0338348/?ref_=nv_sr_srsg_0_tt_6_nm_0_q_The%2520Polar%2520Express",
         metascore: 61,
         metaurl: "https://www.metacritic.com/movie/the-polar-express/",
         tommato: 56,
         tomattoaudience: 64,
         tomattourl: "https://www.rottentomatoes.com/m/polar_express",
         laguange: Engleski,
         trailer: "f0oyHtZiJJs",
         story: `Ovo je priča o mladom dječaku heroju koji se ukrcava u moćni magični voz koji je krenuo ka Sjevernom polu i domu Djeda Mraza na Badnje veče. Tokom ove vožnje, on kreće na putovanje samootkrivanja koje mu pokazuje da čudo života nikada ne blijedi za one koji vjeruju.`,
         director: ["Robert Zemeckis"],
         writers: ["Chris Van Allsburg", "Robert Zemeckis", "William Broyles Jr."],
         actors: ["Tom Hanks", "Chris Coppola", "Michael Jeter"],
         releaseDate: "November 10, 2004",
         runtime: "1h 40m",
         comments: {
            Nikola: ["Ne bih ga gledao opet", "20. Jul 2022."],
            Ana: ["Savršeno!", "28. Jul 2022."],
            Stefan: ["Nešto sasvim novo!", "5. Aug 2022."],
         },
      },
      {
         id: "21",
         img: "/spirited.jpg",
         label: "Spirited Away",
         text: "Tokom selidbe njene porodice u predgrađe, mrzovoljna desetogodišnja devojčica odluta u svet kojim vladaju bogovi, veštice i duhovi, svet u kome se ljudi menjaju u zveri.",
         quality: HD,
         genre: [Animirani, Avantura, Familijarni],
         year: 2001,
         imdb: 8.6,
         imdburl: "https://www.imdb.com/title/tt0245429/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Spirited%2520Away",
         metascore: 96,
         metaurl: "https://www.metacritic.com/movie/spirited-away/",
         tommato: 98,
         tomattoaudience: 98,
         tomattourl: "https://www.rottentomatoes.com/m/spirited_away_studio_ghibli_fest_2018",
         laguange: Engleski,
         trailer: "ByXuk9QqQkk",
         story: `Fantastične avanture desetogodišnje devojčice po imenu Čihiro, koja otkriva tajni svet kada se ona i njena porodica izgube i krenu kroz tunel na padini brda. Kada njeni roditelji prolaze kroz misterioznu transformaciju, Chihiro mora da se brine sama za sebe dok susreće čudne duhove, različita stvorenja i mrzovoljna čarobnica koja je pokušava sprečiti da se vrati u ljudski svet.`,
         director: ["Hayao Miyazaki"],
         writers: ["Hayao Miyazaki"],
         actors: ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino"],
         releaseDate: "March 28, 2003",
         runtime: "2h 5m",
         comments: {
            Tamara: ["Iznenađujuće dobar", "13. Jun 2022."],
            Jovan: ["Moglo je bolje", "21. Jun 2022."],
            Luka: ["Nisam očekivao ovakav kraj", "29. Jun 2022."],
         },
      },
      {
         id: "22",
         img: "/kfpanda.jpg",
         label: "Kung Fu Panda",
         text: "Na svačije iznenađenje, uključujući i njegovo, Po, debela, nespretna panda, izabrana je za zaštitnika Doline mira. Njegova podobnost će uskoro biti testirana jer je najveći neprijatelj doline na putu.",
         quality: HD,
         genre: [Animirani, Akcija, Avantura],
         year: 2008,
         imdb: 7.6,
         imdburl: "https://www.imdb.com/title/tt0441773/?ref_=nv_sr_srsg_3_tt_8_nm_0_q_Kung%2520Fu%2520Panda",
         metascore: 74,
         metaurl: "https://www.metacritic.com/movie/kung-fu-panda/",
         tommato: 87,
         tomattoaudience: 83,
         tomattourl: "https://www.rottentomatoes.com/m/kung_fu_panda",
         laguange: Engleski,
         trailer: "NRc-ze7Wrxw",
         story: `To je priča o lijenoj, nepoštenoj ljenčari pandi, po imenu Po, koji je najveći obožavatelj Kung Fua... što baš i nije od koristi dok radi svaki dan u porodičnoj prodavnici rezanaca. Neočekivano izabran da ispuni drevno proročanstvo, Poovi snovi postaju stvarnost kada se pridruži svetu Kung Fua i uči zajedno sa svojim idolima, legendarnom Besnom petorkom -- Tigrica, Ždral, Bogomoljka, Viper i Majmun -- pod vođstvom njihovog gurua, Učitelju Šifu. Ali prije nego što oni to shvate, osvetoljubivi i podmukli snježni leopard Tai Lung kreće na njihov put, a na Pou je da odbrani sve od nadolazeće prijetnje. Može li svoje snove da postane majstor Kung Fua pretvoriti u stvarnost? Po stavlja svoje srce - i svoj obim - u zadatak, a nevjerovatni heroj na kraju otkriva da su njegove najveće slabosti njegove najveće snage.`,
         director: ["Mark Osborne", "John Stevenson"],
         writers: ["Jonathan Aibel", "Glenn Berger", "Ethan Reiff"],
         actors: ["Jack Black", "Ian McShane", "Angelina Jolie"],
         releaseDate: "June 6, 2008",
         runtime: "1h 32m",
         comments: {
            Jovana: ["Nisam loš film, ali nije za svakoga", "6. May 2022."],
            Nemanja: ["Zabavan film", "14. May 2022."],
            Marija: ["Očekivala sam više", "22. May 2022."],
         },
      },
      {
         id: "23",
         img: "/movingcastle.jpg",
         label: "Howl's Moving Castle",
         text: "Kada zlobna vještica prokleta mladu ženu sa starim tijelom, njena jedina šansa da razbije čaroliju leži u samozadovoljnom, ali nesigurnom mladom čarobnjaku i njegovim pratiocima u njegovom hodajućem dvorcu sa nogama.",
         quality: mediumQ,
         genre: [Animirani, Avantura, Familijarni],
         year: 2004,
         imdb: 8.2,
         imdburl: "https://www.imdb.com/title/tt0347149/?ref_=nv_sr_srsg_0_tt_2_nm_1_q_Howl%27s%2520Moving%2520Castle",
         metascore: 82,
         metaurl: "https://www.metacritic.com/movie/howls-moving-castle/",
         tommato: 87,
         tomattoaudience: 93,
         tomattourl: "https://www.rottentomatoes.com/m/howls_moving_castle",
         laguange: Engleski,
         trailer: "DJeUGpcle8s",
         story: `Budući da je mir u svojoj zemlji stalno ugrožen, Sophie, živahna, ali nevoljena modičarka, privlači pažnju neočekivanog branioca. Ali dok se razrogačena djevojka u nevolji ukršta sa zgodnim Haulom, talentiranim mladim mađioničarom s viškom emocionalnog prtljaga, napad ljubomore zauvijek preokreće svijet tvorca šešira naglavačke. Sada, umrljana neizbrisivim tragom zle Vještice iz pustoši, Sophie mora pomjeriti planine da bi razbila nemilosrdnu čaroliju, uključujući suočavanje sa svojim strahovima i misterioznim čarobnjakom. Međutim, da li je iko ikada kročio u Howlov neprobojni dom, hodajuće čudo koje pokreće vatreno srce, i doživio da ispriča priču?`,
         director: ["Hayao Miyazaki"],
         writers: ["Hayao Miyazaki", "Diana Wynne Jones"],
         actors: ["Chieko Baishô", "Takuya Kimura", "Tatsuya Gashûin"],
         releaseDate: "June 17, 2005",
         runtime: "1h 59m",
         comments: {
            Ivana: ["Najbolji film ikad!", "30. Apr 2022."],
            Milan: ["Očekivao sam bolje", "7. May 2022."],
            Vuk: ["Dosadan film", "15. May 2022."],
         },
      },
      {
         id: "24",
         img: "/creator.jpg",
         label: "The Creator",
         text: "U pozadini rata između ljudi i robota s umjetnom inteligencijom, bivši vojnik pronalazi tajno oružje, robota u obliku malog djeteta.",
         quality: UHD,
         genre: [Akcija, Avantura, Drama],
         year: 2023,
         imdb: 6.9,
         imdburl: "https://www.imdb.com/title/tt11858890/?ref_=nv_sr_srsg_1_tt_6_nm_1_q_The%2520Creator",
         metascore: 63,
         metaurl: "https://www.metacritic.com/movie/the-creator/",
         tommato: 66,
         tomattoaudience: 76,
         tomattourl: "https://www.rottentomatoes.com/m/the_creator_2023",
         laguange: Engleski,
         trailer: "MAZuGdi32bk",
         story: `Usred budućeg rata između ljudske rase i snaga umjetne inteligencije, Joshua, okorjeli bivši agent specijalnih snaga koji tuguje zbog nestanka svoje žene, regrutuje se da lovi i ubije Stvoritelja, neuhvatljivog arhitektu napredne AI koji je razvio misteriozno oružje sa moći da okonča rat - i samo čovečanstvo.`,
         director: ["Gareth Edwards"],
         writers: ["Gareth Edwards", "Chris Weitz"],
         actors: ["John David Washington", "Madeleine Yuna Voyles", "Gemma Chan"],
         releaseDate: "September 29, 2023",
         runtime: "2h 13m",
         comments: {
            Nikola: ["Sjajan scenarij", "23. Mar 2022."],
            Sara: ["Nije loše, ali ništa posebno", "31. Mar 2022."],
            Andrija: ["Nešto sasvim novo!", "7. Apr 2022."],
         },
      },
      {
         id: "25",
         img: "/flowermoon.jpg",
         label: "Killers of the Flower Moon",
         text: "Kada je 1920-ih u Oklahomi otkrivena nafta pod zemljom Osage Nationa, ljudi Osagea bivaju ubijeni jedan po jedan - sve dok FBI ne uskoči da razotkrije misteriju.",
         quality: UHD,
         genre: [Krimi, Drama, Istorijski, Romantični],
         year: 2023,
         imdb: 7.8,
         imdburl: "https://www.imdb.com/title/tt5537002/?ref_=nv_sr_srsg_1_tt_4_nm_3_q_Killers%2520of%2520the%2520Flower%2520Moon",
         metascore: 89,
         metaurl: "https://www.metacritic.com/movie/killers-of-the-flower-moon/",
         tommato: 93,
         tomattoaudience: 84,
         tomattourl: "https://www.rottentomatoes.com/m/killers_of_the_flower_moon",
         laguange: Engleski,
         trailer: "EP34Yoxs3FQ",
         story: `Radnja se odvija 1920-ih oko indijanskog plemena Osage koji živi u Oklahomi. Indijanci se ubijaju jedan po jedan nakon što se pleme obogati otkrivanjem nafte. Masakr u Osageu privlači pažnju FBI-a, koji započinje istragu.`,
         director: ["Martin Scorsese"],
         writers: ["Eric Roth", "Martin Scorsese", "David Grann"],
         actors: ["Leonardo DiCaprio", "Robert De Niro", "Lily Gladstone"],
         releaseDate: "October 20, 2023",
         runtime: "3h 26m",
         comments: {
            Jelena: ["Nisam očekivao/la ovakav kraj", "14. Feb 2022."],
            Dusan: ["Bolje nego što sam očekivao", "22. Feb 2022."],
            Katarina: ["Gubi se radnja", "2. Mar 2022."],
         },
      },
      {
         id: "26",
         img: "/holiday.jpg",
         label: "The Holiday",
         text: "Two women troubled with guy-problems swap homes in each other's countries, where they each meet a local guy and fall in love.",
         quality: lowQ,
         genre: [Komedija, Romantični],
         year: 2006,
         imdb: 6.9,
         imdburl: "https://www.imdb.com/title/tt0457939/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_The%2520Holiday",
         metascore: 52,
         metaurl: "https://www.metacritic.com/movie/the-holiday/",
         tommato: 50,
         tomattoaudience: 80,
         tomattourl: "https://www.rottentomatoes.com/m/the_holiday",
         laguange: Engleski,
         trailer: "wk9caHO3pW0",
         story: `In London, Iris Simpkins writes a wedding column in a newspaper and nurtures an unrequited love for her colleague Jasper Bloom. Near Christmas, she is informed that Jasper is engaged to marry another colleague, and her life turns upside down. In Los Angeles, the movie-trailers maker Amanda Woods has just split with her unfaithful boyfriend Ethan and wants to forget him. Through a house exchange website, Amanda impulsively swaps her mansion for Iris' cottage in Surrey for the holidays. While in Surrey, Amanda meets Iris' brother and book editor Graham and they fall in love with each other. Meanwhile, Iris meets her new next door neighbor the ninety year old screenplay writer Arthur, who helps her retrieve her self-esteem, and the film composer Miles, with whom she falls in love. `,
         director: ["Nancy Meyers"],
         writers: ["Nancy Meyers"],
         actors: ["Kate Winslet", "Cameron Diaz", "Jude Law", "Jack Black"],
         releaseDate: "December 8, 2006",
         runtime: "2h 16m",
         comments: {
            Nikola: ["Ne bih ga gledao opet", "10. Jan 2022."],
            Sara: ["Moglo je bolje", "18. Jan 2022."],
            Andrija: ["Zanimljiva radnja", "26. Jan 2022."],
         },
      },
      {
         id: "27",
         img: "/maestro.jpg",
         label: "Maestro",
         text: "This love story chronicles the lifelong relationship of conductor-composer Leonard Bernstein and actress Felicia Montealegre Cohn Bernstein.",
         quality: UHD,
         genre: [Biografija, Drama, Muzički],
         year: 2023,
         imdb: 8.0,
         imdburl: "https://www.imdb.com/title/tt5535276/?ref_=nv_sr_srsg_1_tt_5_nm_2_q_Maestro",
         metascore: 77,
         metaurl: "https://www.metacritic.com/movie/maestro-2023/",
         tommato: 80,
         tomattoaudience: 61,
         tomattourl: "https://www.rottentomatoes.com/m/maestro_2023",
         laguange: Engleski,
         trailer: "gJP2QblqLA0",
         story: `Maestro will tell the complex love story of Leonard and Felicia, a story that spans over 30 years-from the time they met in 1946 at a party and continuing through two engagements, a 25 year marriage, and three children: Jamie Bernstein, Alexander Bernstein and Nina Bernstein Simmons.
         `,
         director: ["Bradley Cooper"],
         writers: ["Bradley Coope", "Josh Singer"],
         actors: ["Carey Mulligan", "Bradley Cooper", "Matt Bomer"],
         releaseDate: "December 20, 2023",
         runtime: "2h 9m",
         comments: {
            Tamara: ["Preporučujem svima!", "3. Dec 2021."],
            Filip: ["Nisam loš film, ali nije za svakoga", "11. Dec 2021."],
            Ivana: ["Gubi se u drugom dijelu", "19. Dec 2021."],
         },
      },
      {
         id: "28",
         img: "/nohard.jpg",
         label: "No Hard Feelings",
         text: "On the brink of losing her home, Maddie finds an intriguing job listing: helicopter parents looking for someone to bring their introverted 19-year-old son out of his shell before college.",
         quality: UHD,
         genre: [Komedija, Romantični],
         year: 2023,
         imdb: 6.4,
         imdburl: "https://www.imdb.com/title/tt15671028/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_No%2520Hard%2520Feelings",
         metascore: 59,
         metaurl: "https://www.metacritic.com/movie/no-hard-feelings/",
         tommato: 70,
         tomattoaudience: 87,
         tomattourl: "https://www.rottentomatoes.com/m/no_hard_feelings_2023",
         laguange: Engleski,
         trailer: "P15S6ND8kbQ",
         story: `Lawrence's character portrays the "ne'er-do-well" who answers a Craigslist ad that was placed to hire a date for an introverted and socially awkward teen boy, by his mother and father, who also just so happens to be preparing for college soon.`,
         director: ["Gene Stupnitsky"],
         writers: ["Gene Stupnitsky", "John Phillips"],
         actors: ["Jennifer Lawrence", "Andrew Barth Feldman", "Laura Benanti"],
         releaseDate: "June 23, 2023",
         runtime: "1h 43m",
         comments: {
            Stefan: ["Ne bih ga preporučio", "26. Nov 2021."],
            Mia: ["Savršeno!", "4. Dec 2021."],
            Vladimir: ["Najbolji film ikad!", "12. Dec 2021."],
         },
      },
      {
         id: "29",
         img: "/wonka.jpg",
         label: "Wonka",
         text: "With dreams of opening a shop in a city renowned for its chocolate, a young and poor Willy Wonka discovers that the industry is run by a cartel of greedy chocolatiers.",
         quality: UHD,
         genre: [Komedija, Familijarni, Muzički],
         year: 2023,
         imdb: 6.5,
         imdburl: "https://www.imdb.com/title/tt6166392/?ref_=nv_sr_srsg_1_tt_5_nm_2_q_Wonka",
         metascore: 6,
         metaurl: "https://www.metacritic.com/movie/wonka/",
         tommato: 83,
         tomattoaudience: 91,
         tomattourl: "https://www.rottentomatoes.com/m/wonka",
         laguange: Engleski,
         trailer: "otNh9bTjXWg",
         story: `With dreams of opening a shop in a city renowned for its chocolate, a young and poor Willy Wonka discovers that the industry is run by a cartel of greedy chocolatiers. x`,
         director: ["Paul King"],
         writers: ["Simon Farnaby", "Paul King", "Roald Dahl"],
         actors: ["Timothée Chalamet", "Gustave Die", "Murray McArthur"],
         releaseDate: "December 15, 2023",
         runtime: "1h 56m",
         comments: {
            Nina: ["Očekivala sam bolje", "20. Oct 2021."],
            Ivan: ["Iznenađujuće dobar", "28. Oct 2021."],
            Milica: ["Jedva čekam nastavak", "5. Nov 2021."],
         },
      },
      {
         id: "30",
         img: "/spiritedmovie.jpg",
         label: "Spirited",
         text: "A musical version of Charles Dickens's story of a miserly misanthrope who is taken on a magical journey.",
         quality: UHD,
         genre: [Komedija, Familijarni, Muzički],
         year: 2022,
         imdb: 6.6,
         imdburl: "https://www.imdb.com/title/tt10999120/?ref_=nv_sr_srsg_3_tt_8_nm_0_q_Spirited",
         metascore: 55,
         metaurl: "https://www.metacritic.com/movie/spirited/",
         tommato: 71,
         tomattoaudience: 81,
         tomattourl: "https://www.rottentomatoes.com/m/spirited",
         laguange: Engleski,
         trailer: "tnAJntI3NNs",
         story: `A musical version of the classic Christmas story by Charles Dickens. A miserly man who treats everyone around him with terrible selfishness finds himself on a fantastical adventure into the three phases of time: past, present, and future, in order to discover how he ended up so miserable and alone.`,
         director: ["Sean Anders"],
         writers: ["Sean Anders", "John Morris", "Charles Dickens"],
         actors: ["Will Ferrell", "Ryan Reynolds", "Octavia Spencer"],
         releaseDate: "November 18, 2022",
         runtime: "2h 7m",
         comments: {
            Marko: ["Nisam očekivao ovakav kraj", "13. Sep 2021."],
            Teodora: ["Bolje nego što sam očekivala", "21. Sep 2021."],
            Aleksandar: ["Zanimljiva priča", "29. Sep 2021."],
         },
      },
      {
         id: "31",
         img: "/amricanhorror.jpg",
         label: "American Horror Story",
         text: "An anthology series centering on different characters and locations, showcasing different aspects of horror.",
         quality: lowQ,
         genre: [Drama, SciFi, Horor],
         year: 2011,
         imdb: 8.0,
         imdburl: "https://www.imdb.com/title/tt1844624/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_American%2520Horror%2520Story",
         metascore: 65,
         metaurl: "https://www.metacritic.com/tv/american-horror-story/",
         tommato: 77,
         tomattoaudience: 68,
         tomattourl: "https://www.rottentomatoes.com/tv/american_horror_story",
         laguange: Engleski,
         trailer: "nLJR2twdK00",
         story: `Physical and psychological horrors affect a decomposing family, workers and residents of an insane asylum, a coven of witches, a cast of circus freaks, the employees and guests at a struggling hotel, a family who moved into a mysterious farmhouse, the members of a small suburb in Michigan, the surviving members of the Apocalypse and the counselors of a creepy summer camp in this haunting anthology series, focusing on the themes of infidelity, sanity, oppression, discrimination, addiction and exploitation.`,
         director: ["Brad Falchuk", "Ryan Murphy", "Halley Feiffer"],
         writers: ["Brad Falchuk", "Ryan Murphy", "Halley Feiffer"],
         actors: ["Lady Gaga", "Kathy Bates", "Angela Bassett"],
         releaseDate: "October 5, 2011 ",
         runtime: "1h",
         comments: {
            Nikola: ["Moglo je bolje", "6. Aug 2021."],
            Ana: ["Nisam mogao prestati gledati!", "14. Aug 2021."],
            Stefan: ["Nešto sasvim novo!", "22. Aug 2021."],
         },
      },
      {
         id: "32",
         img: "/x.jpg",
         label: "X",
         text: "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.",
         quality: UHD,
         genre: [Horor, Triler],
         year: 2022,
         imdb: 6.5,
         imdburl: "https://www.imdb.com/title/tt13560574/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_x",
         metascore: 79,
         metaurl: "https://www.metacritic.com/movie/x-2022/",
         tommato: 94,
         tomattoaudience: 75,
         tomattourl: "https://www.rottentomatoes.com/m/x_2022",
         laguange: Engleski,
         trailer: "Awg3cWuHfoc",
         story: `Set in 1979, adult movie actors and a small film crew arrive to a farmhouse occupied by an elderly couple in the desolate Texas countryside to film an adult movie. As the day shifts to night, the visitors slowly realize that they are not safe, and are being targeted by a nearby enemy.`,
         director: ["Ti West"],
         writers: ["Ti West"],
         actors: ["Mia Goth", "Jenna Ortega", "Brittany Snow"],
         releaseDate: "March 18, 2022",
         runtime: "1h 45m",
         comments: {
            Tamara: ["Očekivala sam više", "30. Jul 2021."],
            Jovan: ["Nisam loš film, ali nije za svakoga", "7. Aug 2021."],
            Luka: ["Sjajan scenarij", "15. Aug 2021."],
         },
      },
      {
         id: "33",
         img: "/talktome.jpg",
         label: "Talk to Me",
         text: "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
         quality: HD,
         genre: [Horor, Triler],
         year: 2022,
         imdb: 7.1,
         imdburl: "https://www.imdb.com/title/tt10638522/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Talk%2520to%2520Me",
         metascore: 76,
         metaurl: "https://www.metacritic.com/movie/talk-to-me-2022/",
         tommato: 94,
         tomattoaudience: 82,
         tomattourl: "https://www.rottentomatoes.com/m/talk_to_me_2023",
         laguange: Engleski,
         trailer: "aLAKJu9aJys",
         story: `When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and opens the door to the spirit world forcing them to choose who to trust: the dead or the living.`,
         director: ["Danny Philippou", "Michael Philippou"],
         writers: ["Danny Philippou", "Bill Hinzman", "Daley Pearson"],
         actors: ["Ari McCarthy", "Hamish Phillips", "Kit Erhart-Bruce"],
         releaseDate: "July 28, 2023",
         runtime: "1h 35m",
         comments: {
            Jovana: ["Dosadan film", "23. Jun 2021."],
            Nemanja: ["Nisam očekivao ovakav kraj", "1. Jul 2021."],
            Marija: ["Ne bih ga preporučila", "9. Jul 2021."],
         },
      },
      {
         id: "34",
         img: "/from.jpg",
         label: "From",
         text: "Unravel the mystery of a city in middle U.S.A. that imprisons everyone who enters. As the residents struggle to maintain a sense of normality and seek a way out, they must also survive the threats of the surrounding forest.",
         quality: HD,
         genre: [Horor, Triler],
         year: 2022,
         imdb: 7.7,
         imdburl: "https://www.imdb.com/title/tt9813792/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_From",
         metascore: 63,
         metaurl: "https://www.metacritic.com/tv/from/",
         tommato: 94,
         tomattoaudience: 85,
         tomattourl: "https://www.rottentomatoes.com/tv/from",
         laguange: Engleski,
         trailer: "5KvMLgeh3jA",
         story: `Unravels the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normality and search for a way out, they must also survive the threats of the surrounding forest; including the terrifying creatures that come out when the sun goes down.`,
         director: ["John Griffin"],
         writers: ["John Griffin"],
         actors: ["Harold Perrineau", "Catalina Sandino Moreno", "Eion Bailey"],
         releaseDate: "February 20, 2022",
         runtime: "52m",
         comments: {
            Ivana: ["Preporučujem svima!", "17. May 2021."],
            Milan: ["Savršeno!", "25. May 2021."],
            Vuk: ["Najbolji film ikad!", "2. Jun 2021."],
         },
      },
      {
         id: "35",
         img: "/napoleon.jpg",
         label: "Napoleon",
         text: "An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.",
         quality: UHD,
         genre: [Akcija, Avantura, Biografija],
         year: 2023,
         imdb: 6.6,
         imdburl: "https://www.imdb.com/title/tt13287846/?ref_=nv_sr_srsg_0_tt_7_nm_1_q_Napoleon",
         metascore: 64,
         metaurl: "https://www.metacritic.com/movie/napoleon-2023/",
         tommato: 58,
         tomattoaudience: 59,
         tomattourl: "https://www.rottentomatoes.com/m/napoleon_2023",
         laguange: Engleski,
         trailer: "OAZWXUkrjPc",
         story: `Napoleon is a spectacle-filled action epic that details the checkered rise and fall of the iconic French Emperor Napoleon Bonaparte, played by Oscar®-winner Joaquin Phoenix. Against a stunning backdrop of large-scale filmmaking orchestrated by legendary director Ridley Scott, the film captures Bonaparte's relentless journey to power through the prism of his addictive, volatile relationship with his one true love, Josephine, showcasing his visionary military and political tactics against some of the most dynamic practical battle sequences ever filmed. `,
         director: ["Ridley Scott"],
         writers: ["David Scarpa"],
         actors: ["Joaquin Phoenix", "Vanessa Kirby", "Tahar Rahim"],
         releaseDate: "November 22, 2023",
         runtime: "2h 38m",
         comments: {
            Nikola: ["Gubi se radnja", "10. Apr 2021."],
            Luka: ["Moraš ga pogledati!", "18. Apr 2021."],
            Ana: ["Nije loše, ali ništa posebno", "26. Apr 2021."],
         },
      },
      {
         id: "36",
         img: "/wolfwall.jpg",
         label: "The Wolf of Wall Street",
         text: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
         quality: HD,
         genre: [Biografija, Komedija, Krimi],
         year: 2013,
         imdb: 8.2,
         imdburl: "https://www.imdb.com/title/tt0993846/?ref_=nv_sr_srsg_0_tt_5_nm_3_q_The%2520Wolf%2520of%2520Wall%2520Street",
         metascore: 75,
         metaurl: "https://www.metacritic.com/movie/the-wolf-of-wall-street/",
         tommato: 80,
         tomattoaudience: 86,
         tomattourl: "https://www.rottentomatoes.com/m/the_wolf_of_wall_street_2013",
         laguange: Engleski,
         trailer: "iszwuX1AK6A",
         story: `Jordan Belfort (DiCaprio) is Long Island penny stockbroker who serves almost two years in prison for refusing to co-operate in a huge 1990s securities fraud case that involved widespread corruption on Wall Street and in the corporate banking world, including mob infiltration.`,
         director: ["Martin Scorsese"],
         writers: ["Terence Winter", "Jordan Belfort"],
         actors: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"],
         releaseDate: "December 25, 2013",
         runtime: "3h",
         comments: {
            Tamara: ["Ne bih ga gledala opet", "4. Mar 2021."],
            Filip: ["Zabavan film", "12. Mar 2021."],
            Ivana: ["Očekivala sam bolje", "20. Mar 2021."],
         },
      },
      {
         id: "37",
         img: "/opnh.jpg",
         label: "Oppenheimer",
         text: "The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.",
         quality: UHD,
         genre: [Biografija, Drama, Istorijski],
         year: 2023,
         imdb: 8.4,
         imdburl: "https://www.imdb.com/title/tt15398776/?ref_=nv_sr_srsg_1_tt_3_nm_4_q_Oppenheimer",
         metascore: 89,
         metaurl: "https://www.metacritic.com/movie/oppenheimer/",
         tommato: 93,
         tomattoaudience: 91,
         tomattourl: "https://www.rottentomatoes.com/m/oppenheimer_2023",
         laguange: Engleski,
         trailer: "uYPbbksJxIg",
         story: `A dramatization of the life story of J. Robert Oppenheimer, the physicist who had a large hand in the development of the atomic bomb, thus helping end World War 2. We see his life from university days all the way to post-WW2, where his fame saw him embroiled in political machinations.`,
         director: ["Christopher Nolan"],
         writers: ["Christopher Nolan", "Kai Bird", "Martin Sherwin"],
         actors: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
         releaseDate: "July 21, 2023",
         runtime: "3h",
         comments: "",
      },
      {
         id: "38",
         img: "/soundsilence.jpg",
         label: "Sound of Freedom",
         text: "The incredible true story of a former government agent turned vigilante who embarks on a dangerous mission to rescue hundreds of children from traffickers.",
         quality: UHD,
         genre: [Biografija, Krimi, Drama],
         year: 2023,
         imdb: 7.7,
         imdburl: "https://www.imdb.com/title/tt7599146/?ref_=nv_sr_srsg_0_tt_7_nm_1_q_Sound%2520of%2520Freedom",
         metascore: 36,
         metaurl: "https://www.metacritic.com/movie/sound-of-freedom/",
         tommato: 57,
         tomattoaudience: 99,
         tomattourl: "https://www.rottentomatoes.com/m/sound_of_freedom",
         laguange: Engleski,
         trailer: "Rt0kp4VW1cI",
         story: `"Sound of Freedom", based on the incredible true story, shines a light on even the darkest of places. After rescuing a young boy from ruthless child-traffickers, a federal agent learns that the boy's sister is still a captive and decides to embark on a dangerous mission to save her. With time running out, he quits his job and journeys deep into the Colombian jungle, putting his life on the line to free her from a fate worse than death.`,
         director: ["Alejandro Monteverde"],
         writers: ["Rod Barr", "Alejandro Monteverde"],
         actors: ["Jim Caviezel", "Mira Sorvino", "Bill Camp"],
         releaseDate: "July 4, 2023",
         runtime: "2h 11m",
         comments: "",
      },
      {
         id: "39",
         img: "/growold.jpg",
         label: "They Shall Not Grow Old",
         text: "A documentary about World War I with never-before-seen footage to commemorate the centennial of the end of the war.",
         quality: mediumQ,
         genre: [Dokumentarni, Istorijski, Ratni],
         year: 2018,
         imdb: 8.2,
         imdburl: "https://www.imdb.com/title/tt7905466/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_They%2520Shall%2520Not%2520Grow%2520Old",
         metascore: 91,
         metaurl: "https://www.metacritic.com/movie/they-shall-not-grow-old/",
         tommato: 99,
         tomattoaudience: 91,
         tomattourl: "https://www.metacritic.com/movie/they-shall-not-grow-old/",
         laguange: Engleski,
         trailer: "IrabKK9Bhds",
         story: `Through ground breaking computer restoration technology, filmmaker Peter Jackson's team creates a moving real-to-life depiction of the WWI, as never seen before in restored, vivid colorizing & retiming of the film frames, in order to honor those who fought and more accurately depict this historical moment in world history. `,
         director: ["Peter Jackson"],
         writers: ["Peter Jackson"],
         actors: ["Thomas Adlam", "William Argent", "John Ashby"],
         releaseDate: "February 1, 2019",
         runtime: "1h 39m",
         comments: "",
      },
      {
         id: "41",
         img: "/leaveworld.jpg",
         label: "Leave the World Behind",
         text: "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices, and two strangers appear at their door.",
         quality: mediumQ,
         genre: [Drama, Triler],
         year: 2014,
         imdb: 7.7,
         imdburl: "https://www.imdb.com/title/tt12747748/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Leave%2520the%2520World%2520Behind",
         metascore: 68,
         metaurl: "https://www.metacritic.com/movie/leave-the-world-behind/",
         tommato: 76,
         tomattoaudience: 34,
         tomattourl: "https://www.rottentomatoes.com/m/leave_the_world_behind_2023",
         laguange: Engleski,
         trailer: "cMVBi_e8o-Y",
         story: `Amanda and Clay's aspirational vacation with their teenage children is interrupted by the arrival of a middle aged man and his daughter who own the holiday home and who have fled an unprecedented blackout in the city. When the internet, television and radio stop working, as does the landline, they have no way of finding out what is happening. As strange sonic booms shatter the peace of the countryside, and animals start to migrate in strange ways, the physical and mental health of the families begins to disintegrate. The renters are upscale and White; the owners are upscale and Black. The issues of race clash and become distractions to the more alarming things that are happening all around them.`,
         director: ["Sam Esmail"],
         writers: ["Rumaan Alam", "Sam Esmail"],
         actors: ["Julia Roberts", "Mahershala Ali", "Ethan Hawke"],
         releaseDate: "December 8, 2023",
         runtime: "2h 18m",
         comments: "",
      },
      {
         id: "42",
         img: "/outlaw.jpg",
         label: "The Outlaw Josey Wales",
         text: "Missouri farmer Josey Wales joins a Confederate guerrilla unit and winds up on the run from the Union soldiers who murdered his family.",
         quality: lowQ,
         genre: [Vestern],
         year: 1976,
         imdb: 7.8,
         imdburl: "https://www.imdb.com/title/tt0075029/?ref_=nv_sr_srsg_0_tt_3_nm_0_q_The%2520Outlaw%2520Josey%2520Wal",
         metascore: 69,
         metaurl: "https://www.metacritic.com/movie/the-outlaw-josey-wales/",
         tommato: 91,
         tomattoaudience: 91,
         tomattourl: "https://www.rottentomatoes.com/m/outlaw_josey_wales",
         laguange: Engleski,
         trailer: "dCPcoNo_OkM",
         story: `Josey Wales (Clint Eastwood) makes his way west after the Civil War, determined to live a useful and helpful life. He joins up with a group of settlers who need the protection that a man as tough and experienced as he is can provide. Unfortunately, the past has a way of catching up with you, and Josey is a wanted man.`,
         director: ["Clint Eastwood"],
         writers: ["Forrest Carter", "Philip Kaufman", "Sonia Chernus"],
         actors: ["Clint Eastwood", "Sondra Locke", "Chief Dan George"],
         releaseDate: "June 30, 1976",
         runtime: "2h 15m",
         comments: "",
      },
      {
         id: "43",
         img: "/revenant.jpg",
         label: "The Revenant",
         text: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
         quality: UHD,
         genre: [Akcija, Avantura, Drama, Vestern],
         year: 2015,
         imdb: 8.0,
         imdburl: "https://www.imdb.com/title/tt1663202/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_The%2520Revenant",
         metascore: 76,
         metaurl: "https://www.metacritic.com/movie/the-revenant-2015/",
         tommato: 78,
         tomattoaudience: 84,
         tomattourl: "https://www.rottentomatoes.com/m/the_revenant_2015",
         laguange: Engleski,
         trailer: "LoebZZ8K5N0",
         story: `While exploring uncharted wilderness in 1823, legendary frontiersman Hugh Glass sustains injuries from a brutal bear attack. When his hunting team leaves him for dead, Glass must utilize his survival skills to find a way back home while avoiding natives on their own hunt. Grief-stricken and fueled by vengeance, Glass treks through the wintry terrain to track down John Fitzgerald, the former confidant who betrayed and abandoned him.`,
         director: ["Alejandro G. Iñárritu"],
         writers: ["Mark L. Smith", "Alejandro G. Iñárritu", "Michael Punke"],
         actors: ["Leonardo DiCaprio", "Tom Hardy", "Will Poulter"],
         releaseDate: "January 8, 2016",
         runtime: "2h 36m",
         comments: "",
      },
      {
         id: "44",
         img: "/hateful.jpg",
         label: "The Hateful Eight",
         text: "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
         quality: mediumQ,
         genre: [Krimi, Drama, Vestern],
         year: 2015,
         imdb: 7.8,
         imdburl: "https://www.imdb.com/title/tt3460252/?ref_=nv_sr_srsg_0_tt_4_nm_0_q_The%2520Hateful%2520Eight",
         metascore: 68,
         metaurl: "https://www.metacritic.com/movie/the-hateful-eight/",
         tommato: 75,
         tomattoaudience: 77,
         tomattourl: "https://www.rottentomatoes.com/m/the_hateful_eight",
         laguange: Engleski,
         trailer: "nIOmotayDMY",
         story: `Some time after the Civil War, a stagecoach hurtles through the wintry Wyoming landscape. Bounty hunter John Ruth and his fugitive captive Daisy Domergue race towards the town of Red Rock, where Ruth will bring Daisy to justice. Along the road, they encounter Major Marquis Warren (an infamous bounty hunter) and Chris Mannix (a man who claims to be Red Rock's new sheriff). Lost in a blizzard, the bunch seeks refuge at Minnie's Haberdashery. When they arrive they are greeted by unfamiliar faces: Bob, who claims to be taking care of the place while Minnie is gone; Oswaldo Mobray, the hangman of Red Rock; Joe Gage, a cow puncher; and confederate general Sanford Smithers. As the storm overtakes the mountainside, the eight travelers come to learn that they might not make it to Red Rock after all...`,
         director: ["Quentin Tarantino"],
         writers: ["Quentin Tarantino"],
         actors: ["Samuel L. Jackson", "Kurt Russell", "Jennifer Jason Leigh"],
         releaseDate: "December 30, 2015",
         runtime: "2h 48m",
         comments: "",
      },
      {
         id: "45",
         img: "/toombstone.jpg",
         label: "Tombstone",
         text: "A successful lawman's plans to retire anonymously in Tombstone, Arizona are disrupted by the kind of outlaws he was famous for eliminating.",
         quality: lowQ,
         genre: [Biografija, Drama, Istorijski, Vestern],
         year: 1993,
         imdb: 7.8,
         imdburl: "https://www.imdb.com/title/tt0108358/?ref_=nv_sr_srsg_0_tt_7_nm_1_q_Tombstone",
         metascore: 50,
         metaurl: "https://www.metacritic.com/movie/tombstone/",
         tommato: 73,
         tomattoaudience: 94,
         tomattourl: "https://www.rottentomatoes.com/m/tombstone",
         laguange: Engleski,
         trailer: "QPTVLKKgGXw",
         story: `After success cleaning up Dodge City, Wyatt Earp moves to Tombstone, Arizona, and wishes to get rich in obscurity. He meets his brothers there, as well as his old friend Doc Holliday. A band of outlaws that call themselves The Cowboys are causing problems in the region with various acts of random violence, and inevitably come into confrontation with Holliday and the Earps, which leads to a shoot-out at the O.K. Corral. `,
         director: ["George P. Cosmatos", "Kevin Jarre"],
         writers: ["Kevin Jarre"],
         actors: ["Kurt Russell", "Val Kilmer", "Sam Elliott"],
         releaseDate: "December 25, 1993",
         runtime: "2h 10m",
         comments: "",
      },
      {
         id: "46",
         img: "/pljackarajha.jpg",
         label: "Pljacka treceg rajha",
         text: "During 1941 in Belgrade, two well-known thieves try to carry out the biggest robbery of Nazi authorities ever",
         quality: lowQ,
         genre: [Komedija, Ratni],
         year: 2004,
         imdb: 6.5,
         imdburl: "https://www.imdb.com/title/tt0374128/?ref_=nv_sr_srsg_0_tt_1_nm_0_q_Pljacka%2520treceg%2520rajha",
         metascore: 0,
         metaurl: "",
         tommato: 0,
         tomattoaudience: 0,
         tomattourl: "",
         laguange: Engleski,
         trailer: "ZxEpKZj3Gw4",
         story: ``,
         director: ["Zdravko Sotra"],
         writers: ["Miodrag Andric"],
         actors: ["Dragan Nikolic", "Nikola Djuricko", "Katarina Zutic"],
         releaseDate: "February 16, 2004",
         runtime: "1h 45m",
         comments: "",
      },
      {
         id: "47",
         img: "/django.jpg",
         label: "Django Unchained",
         text: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.",
         quality: mediumQ,
         genre: [Drama, Vestern],
         year: 2012,
         imdb: 8.5,
         imdburl: "https://www.imdb.com/title/tt1853728/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Django%2520Unchained",
         metascore: 81,
         metaurl: "https://www.metacritic.com/movie/django-unchained/",
         tommato: 87,
         tomattoaudience: 92,
         tomattourl: "https://www.rottentomatoes.com/m/django_unchained_2012",
         laguange: Engleski,
         trailer: "0fUCuvNlOCg",
         story: `In 1858, a bounty-hunter named King Schultz seeks out a slave named Django and buys him because he needs him to find some men he is looking for. After finding them, Django wants to find his wife, Broomhilda, who along with him were sold separately by his former owner for trying to escape. Schultz offers to help him if he chooses to stay with him and be his partner. Eventually they learn that she was sold to a plantation in Mississippi. Knowing they can't just go in and say they want her, they come up with a plan so that the owner will welcome them into his home and they can find a way.`,
         director: ["Quentin Tarantino"],
         writers: ["Quentin Tarantino"],
         actors: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"],
         releaseDate: "December 25, 2012",
         runtime: "2h 45m",
         comments: "",
      },
      {
         id: "48",
         img: "/maratonci.jpg",
         label: "Maratonci trce pocasni krug",
         text: "The Topalovic family has been in the burial business for generations. When the old (150 yrs old) Pantelija dies, five generations of his heirs start to fight for the inheritance.",
         quality: lowQ,
         genre: [Komedija, Drama],
         year: 1982,
         imdb: 8.8,
         imdburl: "https://www.imdb.com/title/tt0084302/?ref_=nv_sr_srsg_0_tt_1_nm_0_q_Maratonci%2520trce%2520pocasni%2520krug",
         metascore: 0,
         metaurl: "",
         tommato: 0,
         tomattoaudience: 100,
         tomattourl: "https://www.rottentomatoes.com/m/the_marathon_family",
         laguange: Domaci,
         trailer: "KvOof9MSjcE",
         story: `The story is set between the two World Wars. The Topalovic family consists of five generations of males: the youngest is 25 and the oldest is 120. Conflicts break out in the family because the youngest member refuses to carry on the morticians' trade, which for decades, from generation to generation, has been his family's occupation. The manufacturing of coffins is more and more lucrative, new technologies are introduced, burials are faster and easier, the crematoria era is here. But the youngest member of the family, Mirko, is not interested. He believes in a "better, nicer and more honest occupation". In this belief he is supported and encouraged by his girlfriend Kristina and his best friend Djenka, owner of a small cinema. Kristina's father Billy Python, supplier of coffins to the Topalovic company, demands a larger share in the earnings, i.e. a fair division of work and profit. Thus these two families come into conflict. In the showdown all means are permitted. This is American gangsterism in Balkan style. Greatly disappointed because both his friend and his girlfriend betrayed him, Mirko commits murder. As a murderer, he returns to his family where he is received with open arms as the new leader of the family, aware of his strength and power, a representative of the new generation whose basic moral principle is ruthlessness.`,
         director: ["Slobodan Sijan"],
         writers: ["Dusan Kovacevic"],
         actors: ["Bogdan Diklic", "Danilo 'Bata' Stojkovic", "Pavle Vuisic"],
         releaseDate: "March 4, 1982",
         runtime: "1h 32m",
         comments: "",
      },
      {
         id: "49",
         img: "/munje.jpg",
         label: "Munje",
         text: "Just an ordinary urban Belgrade night - two friends are trying to get their money back from their school friend, whom they bullied when they were kids.",
         quality: lowQ,
         genre: [Komedija],
         year: 2001,
         imdb: 7.9,
         imdburl: "https://www.imdb.com/title/tt0279248/?ref_=nv_sr_srsg_1_tt_6_nm_2_q_Munje",
         metascore: 0,
         metaurl: "",
         tommato: 0,
         tomattoaudience: 0,
         tomattourl: "",
         laguange: Domaci,
         trailer: "IHSQH598E0c",
         story: `Urban comedy, happening during a night in Belgrade. Mare, Pop and Gojko are three friends who grew up together. Mare and Pop have always been musicians, while Gojko (who was harassed by them in school and nicknamed 'Sissy') became a 'guy in suit', boss of his own club and recording studio. Pop and Mare call on their friend from school days to help them release the record, but all this doesn't go so smoothly. Gojko hasn't forgotten his school days and now he is surrounded by bodyguards. On their way to the club, Mare and Pop meet false Santa Claus, 'cool' cop and of course - girls.`,
         director: ["Radivoje Andric"],
         writers: ["Srdja Andjelic", "Radivoje Andric"],
         actors: ["Boris Milivojevic", "Sergej Trifunovic", "Maja Mandzuka"],
         releaseDate: "March 21, 2001",
         runtime: "1h 30m",
         comments: "",
      },
      {
         id: "50",
         img: "/bgfantom.jpg",
         label: "Beogradski Fantom",
         text: "The film is about Vlada Vasiljević, a citizen of Belgrade, who in 1979 stole a white Porsche 911 Targa S, and for about ten evenings taunted the police with his reckless driving.",
         quality: lowQ,
         genre: [Dokumentarni, Akcija, Krimi],
         year: 2009,
         imdb: 6.7,
         imdburl: "https://www.imdb.com/title/tt0810089/?ref_=nv_sr_srsg_0_tt_1_nm_0_q_Beogradski%2520Fantom",
         metascore: "?",
         metaurl: "",
         tommato: 0,
         tomattoaudience: 0,
         tomattourl: "",
         laguange: Domaci,
         trailer: "LDGqDZiiq-o",
         story: `Belgrade, Yugoslavia, 1979. While Yugoslav president Tito is in Cuba settling international matters, a mysterious Phantom occupies the attention and hearts of Belgrade. Every night, he exhibits spectacular driving maneuvers using a stolen white Porsche car through the city streets. Through the radio the Phantom publicly challenges the police to try and catch him. More than 10.000 people are in the streets supporting their hero. The police are forced into a game where he sets the rules. The Phantom becomes a political threat. What started as a game turned into a political scandal and remained a myth that would never be forgotten.`,
         director: ["Jovan B. Todorovic"],
         writers: ["Jovan B. Todorovic", "Bogdan Petkovic", "Kosta Pesevski"],
         actors: ["Marko Zivic", "Radoslav 'Rale' Milenkovic", "Nada Macankovica"],
         releaseDate: "",
         runtime: "1h 22m",
         comments: "March 27, 2009",
      },
      {
         id: "51",
         img: "/underground.jpg",
         label: "Underground",
         text: "Two underground black marketeers, Marko and Blacky, sell weapons to the Communist resistance in wartime Belgrade, living the good life along the way.",
         quality: lowQ,
         genre: [Komedija, Drama, Fantazija],
         year: 1995,
         imdb: 8.1,
         imdburl: "https://www.imdb.com/title/tt0114787/?ref_=nm_knf_t_4",
         metascore: 0,
         metaurl: "",
         tommato: 0,
         tomattoaudience: 0,
         tomattourl: "",
         laguange: Domaci,
         trailer: "rYTvmLvLchs",
         story: `The story follows an underground weapons manufacturer in Belgrade during WWII and evolves into fairly surreal situations. A black-marketeer who smuggles the weapons to partisans doesn't mention to the workers that the war is over, and they keep producing. Years later, they break out of their underground "shelter"--only to convince themselves that the war is still going on.`,
         director: ["Emir Kusturica"],
         writers: ["Dusan Kovacevic", "Emir Kusturica"],
         actors: ["Predrag 'Miki' Manojlovic", "Lazar Ristovski", "Mirjana Jokovic"],
         releaseDate: "June 20, 1997",
         runtime: "1995",
         comments: "",
      },
      {
         id: "51",
         img: "/got.jpg",
         label: "Game of Thrones",
         text: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.",
         quality: UHD,
         genre: [Akcija, Avantura, Fantazija],
         year: 2011,
         imdb: 9.2,
         imdburl: "https://www.imdb.com/title/tt0944947/?ref_=sr_t_5",
         metascore: 86,
         metaurl: "https://www.metacritic.com/tv/game-of-thrones/",
         tommato: 88,
         tomattoaudience: 85,
         tomattourl: "https://www.rottentomatoes.com/tv/game_of_thrones",
         laguange: Engleski,
         trailer: "KPLWWIOCOOQ",
         story: `In the mythical continent of Westeros, several powerful families fight for control of the Seven Kingdoms. As conflict erupts in the kingdoms of men, an ancient enemy rises once again to threaten them all. Meanwhile, the last heirs of a recently usurped dynasty plot to take back their homeland from across the Narrow Sea.`,
         director: ["David Benioff", "D.B. Weiss"],
         writers: ["David Benioff", "D.B. Weiss"],
         actors: ["Emilia Clarke", "Peter Dinklage", "Kit Harington"],
         releaseDate: "April 17, 2011",
         runtime: "1h",
         comments: "",
      },
      {
         id: "52",
         img: "/strangerth.jpg",
         label: "Stranger Things",
         text: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
         quality: UHD,
         genre: [Horor, Drama, Fantazija],
         year: 2016,
         imdb: 8.7,
         imdburl: "https://www.imdb.com/title/tt4574334/?ref_=sr_t_10",
         metascore: 74,
         metaurl: "https://www.metacritic.com/tv/stranger-things/",
         tommato: 92,
         tomattoaudience: 90,
         tomattourl: "https://www.rottentomatoes.com/tv/stranger_things",
         laguange: Engleski,
         trailer: "b9EkMc79ZSU",
         story: `In a small town where everyone knows everyone, a peculiar incident starts a chain of events that leads to a child's disappearance, which begins to tear at the fabric of an otherwise-peaceful community. Dark government agencies and seemingly malevolent supernatural forces converge on the town, while a few of the locals begin to understand that more is going on than meets the eye.`,
         director: ["Matt Duffer", "Ross Duffer"],
         writers: ["Matt Duffer", "Ross Duffer"],
         actors: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
         releaseDate: "July 15, 2016",
         runtime: "51m",
         comments: "",
      },
      {
         id: "53",
         img: "/.jpg",
         label: "",
         text: "",
         quality: lowQ,
         genre: [],
         year: 0,
         imdb: 0,
         imdburl: "",
         metascore: 0,
         metaurl: "",
         tommato: 0,
         tomattoaudience: 0,
         tomattourl: "",
         laguange: Engleski,
         trailer: "",
         story: ``,
         director: [""],
         writers: [""],
         actors: [""],
         releaseDate: "",
         runtime: "",
         comments: "",
      },
      {
         id: "54",
         img: "/Supernatural.jpg",
         label: "Supernatural",
         text: "Two brothers follow their father's footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.",
         quality: HD,
         genre: [Drama, Horor, Fantazija],
         year: 2005,
         imdb: 8.4,
         imdburl: "https://www.imdb.com/title/tt0460681/?ref_=sr_t_7",
         metascore: 60,
         metaurl: "https://www.metacritic.com/tv/supernatural/",
         tommato: 93,
         tomattoaudience: 72,
         tomattourl: "https://www.rottentomatoes.com/tv/supernatural",
         laguange: Engleski,
         trailer: "t-775JyzDTk",
         story: `John Winchester raised his two sons Sam and Dean to hunt and kill all things that go "bump in the night" after his wife Mary was murdered by an evil supernatural being when the boys were little. 22 years later the brothers set out on a journey, fighting evil along the way, to find their recently-missing father; when they finally do he reveals he knows what demon killed their mother and has found a way to track and kill it. Meanwhile, Sam develops frightening abilities such as seeing visions of people dying before it actually happens. These visions are somehow connected to the demon that murdered his mother and its mysterious plans that seem to be all about Sam. When their father dies striking a deal with that very same demon, the brothers determine to finish his crusade. But disturbing revelations about Sam's part in the demon's apocalyptic plan are presented when John's dying last words to Dean are revealed. `,
         director: ["Eric Kripke"],
         writers: ["Eric Kripke"],
         actors: ["Jared Padalecki", "Jensen Ackles", "Jim Beaver"],
         releaseDate: "September 13, 2005",
         runtime: "44m",
         comments: "",
      },
      {
         id: "55",
         img: "/TheJoyofPainting.jpg",
         label: "The Joy of Painting",
         text: "In this half-hour program, artist Bob Ross paints a beautiful oil painting on canvas.",
         quality: mediumQ,
         genre: [Dokumentarni, Familijarni],
         year: 1983,
         imdb: 9.3,
         imdburl: "https://www.imdb.com/title/tt0383795/?ref_=sr_i_10",
         metascore: 0,
         metaurl: "",
         tommato: 0,
         tomattoaudience: 0,
         tomattourl: "https://www.rottentomatoes.com/tv/the_joy_of_painting",
         laguange: Engleski,
         trailer: "ov4um2AjBcw",
         story: ``,
         director: [""],
         writers: [""],
         actors: ["Bob Ross", "Steve Ross", "Dana Jester"],
         releaseDate: "January 11, 1983",
         runtime: "25m",
         comments: "",
      },
      {
         id: "56",
         img: "/Penguins.jpg",
         label: "March of the Penguins",
         text: "In the Antarctic, every March since the beginning of time, the quest begins to find the perfect mate and start a family.",
         quality: mediumQ,
         genre: [Dokumentarni, Familijarni],
         year: 2005,
         imdb: 7.5,
         imdburl: "https://www.imdb.com/title/tt0428803/?ref_=sr_i_8",
         metascore: 79,
         metaurl: "https://www.metacritic.com/movie/march-of-the-penguins/",
         tommato: 94,
         tomattoaudience: 81,
         tomattourl: "https://www.rottentomatoes.com/m/march_of_the_penguins",
         laguange: Engleski,
         trailer: "L7tWNwhSocE",
         story: `At the end of each Antarctic summer, the emperor penguins of the South Pole journey to their traditional breeding grounds in a fascinating mating ritual that is captured in this documentary by intrepid filmmaker Luc Jacquet. The journey across frozen tundra proves to be the simplest part of the ritual, as after the egg is hatched, the female must delicately transfer it to the male and make her way back to the distant sea to nourish herself and bring back food to her newborn chick.`,
         director: ["Luc Jacquet"],
         writers: ["Luc Jacquet", "Michel Fessler", "Jordan Roberts"],
         actors: ["Morgan Freeman", "Romane Bohringer", "Charles Berling"],
         releaseDate: "July 22, 2005",
         runtime: "1h 20m",
         comments: "",
      },
      {
         id: "57",
         img: "/Cosmos.jpg",
         label: "Cosmos: Possible Worlds",
         text: "Cosmos: A Spacetime Odyssey returns for a second season. Ann Druyan, original creative collaborator to Carl Sagan, serves as executive producer.",
         quality: HD,
         genre: [Dokumentarni, Animirani, Familijarni],
         year: 2020,
         imdb: 9.0,
         imdburl: "https://www.imdb.com/title/tt11170862/?ref_=sr_i_6",
         metascore: 0,
         metaurl: "https://www.metacritic.com/tv/cosmos-possible-worlds/",
         tommato: 80,
         tomattoaudience: 80,
         tomattourl: "https://www.rottentomatoes.com/tv/cosmos_possible_worlds",
         laguange: Engleski,
         trailer: "QoNSU9o6464",
         story: `Following the wildly successful "Cosmos: A Spacetime Odyssey," Neil deGrasse Tyson returns as host to translate more revelations of science into a lavish transporting experience, taking audiences on a series of spiritual voyages of exploration. The show reveals previously uncharted realms, including lost worlds, worlds yet to come, and the worlds that humans may one day inhabit. Ann Druyan, original creative collaborator to Carl Sagan, whose iconic docuseries "Cosmos" provided inspiration for this series, serves as executive producer alongside Seth MacFarlane.`,
         director: [""],
         writers: [""],
         actors: ["Neil deGrasse Tyson", "Seth MacFarlane", "Sasha Sagan"],
         releaseDate: "March 9, 2020",
         runtime: "45m",
         comments: "",
      },
      {
         id: "58",
         img: "/TheBiggestLittleFarm.jpg",
         label: "The Biggest Little Farm",
         text: "Documentarian John Chester and his wife Molly work to develop a sustainable farm on 200 acres outside of Los Angeles.",
         quality: lowQ,
         genre: [Dokumentarni, Familijarni],
         year: 2018,
         imdb: 8.0,
         imdburl: "https://www.imdb.com/title/tt8969332/?ref_=sr_i_5",
         metascore: 73,
         metaurl: "https://www.metacritic.com/movie/the-biggest-little-farm/",
         tommato: 91,
         tomattoaudience: 95,
         tomattourl: "https://www.rottentomatoes.com/m/the_biggest_little_farm",
         laguange: Engleski,
         trailer: "fcQKWkpPB3U",
         story: `A testament to the immense complexity of nature, The Biggest Little Farm follows two dreamers and a dog on an odyssey to bring harmony to both their lives and the land. When the barking of their beloved dog Todd leads to an eviction notice from their tiny LA apartment, John and Molly Chester make a choice that takes them out of the city and onto 200 acres in the foothills of Ventura County, naively endeavoring to build one of the most diverse farms of its kind in complete coexistence with nature. The land they've chosen, however, is utterly depleted of nutrients and suffering from a brutal drought. The film chronicles eight years of daunting work and outsize idealism as they attempt to create the utopia they seek, planting 10,000 orchard trees and over 200 different crops, and bringing in animals of every kind- including an unforgettable pig named Emma and her best friend, Greasy the rooster. When the farm's ecosystem finally begins to reawaken, so does the Chesters' hope - but as their plan to create perfect harmony takes a series of wild turns, they realize that to survive they will have to reach a far greater understanding of the intricacies and wisdom of nature, and of life itself.`,
         director: ["John Chester"],
         writers: ["Mark Monroe", "John Chester"],
         actors: ["John Chester", "Molly Chester", "Todd"],
         releaseDate: "May 10, 2019",
         runtime: "1h 31m",
         comments: "",
      },
      {
         id: "59",
         img: "/.jpg",
         label: "",
         text: "",
         quality: lowQ,
         genre: [],
         year: 0,
         imdb: 0,
         imdburl: "",
         metascore: 0,
         metaurl: "",
         tommato: 0,
         tomattoaudience: 0,
         tomattourl: "",
         laguange: Engleski,
         trailer: "",
         story: ``,
         director: [""],
         writers: [""],
         actors: [""],
         releaseDate: "",
         runtime: "",
         comments: "",
      },
      {
         id: "60",
         img: "/.jpg",
         label: "",
         text: "",
         quality: lowQ,
         genre: [],
         year: 0,
         imdb: 0,
         imdburl: "",
         metascore: 0,
         metaurl: "",
         tommato: 0,
         tomattoaudience: 0,
         tomattourl: "",
         laguange: Engleski,
         trailer: "",
         story: ``,
         director: [""],
         writers: [""],
         actors: [""],
         releaseDate: "",
         runtime: "",
         comments: "",
      },
   ];
   return movies;
}
